In [ ]:
import numpy as np

Task 1

In [ ]:
A = np.array([[1,2,1],[-2,1,1]])
B = np.array([[3,1],[-1,0],[2,4]])
C = np.array([[-2,2],[1,-1],[1,2]])
#Пробуем сложить матрицы разной размерности с обработкой исключений
try:
  answer_1 = A+B*2
except ValueError:
  print("Размерности матриц не совпадают, сложение невозможно")
print('Поскольку матрицы имеют разные размерности, транспонируем матрицу A')
print('A.T+2B =')
answer_1 = A.T+B*2
print(answer_1)
answer_2 = B+C*2
print('B+2C =')
print(answer_2)

Размерности матриц не совпадают, сложение невозможно
Поскольку матрицы имеют разные размерности, транспонируем матрицу A
A.T+2B =
[[7 0]
 [0 1]
 [5 9]]
B+2C =
[[-1  5]
 [ 1 -2]
 [ 4  8]]


Task 2

In [ ]:
zeroes_matrix = np.zeros((8,8), dtype=int)
zeroes_matrix[1::2,::2] = 1
zeroes_matrix[::2,1::2] = 1
zeroes_matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Task 3

In [ ]:
vect1 = np.linspace(0.0, 1.4, num=15, endpoint=True)
#Также можно через arange, тогда было бы np.arange(0.0, 1.4+0.1, 0.1), прибавляем к последнему элементу шаг для  включения его в вектор
print("Вектор длиной 15 элементов созначениями от 0 до 1,4 с шагом 0,1:")
print(vect1)
vect2 = np.linspace(1, 6, num=6, endpoint=True)
#Также можно через arange, тогда было бы np.arange(1, 6+1, 1), прибавляем к последнему элементу шаг для  включения его в вектор
print("Вектор длиной 6 элементов созначениями от 1 до 6 с шагом 1:")
print(vect2)
matrix_1 = vect1.reshape(5,3)
print("Преобразуем первый вектор в матрицу 5х3:")
print(matrix_1)
matrix_2 = vect2.reshape(3,2)
print("Преобразуем второй вектор в матрицу 3х2:")
print(matrix_2)
matrix_mul = np.matmul(matrix_1,matrix_2)
print("Результат умножения полученных матриц:")
print(matrix_mul)
matrix_mu = np.dot(matrix_1,matrix_2)
print("Результат умножения полученных матриц:")
print(matrix_mu)


Вектор длиной 15 элементов созначениями от 0 до 1,4 с шагом 0,1:
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4]
Вектор длиной 6 элементов созначениями от 1 до 6 с шагом 1:
[1. 2. 3. 4. 5. 6.]
Преобразуем первый вектор в матрицу 5х3:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]
Преобразуем второй вектор в матрицу 3х2:
[[1. 2.]
 [3. 4.]
 [5. 6.]]
Результат умножения полученных матриц:
[[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]
Результат умножения полученных матриц:
[[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]


Task 4

In [ ]:
#Как создать вектор неопределенной длины через numpy, к сожалению, не додумался
k=1
list = [1]
for i in range(35):
  k=k+2
  list.append(k)
vect = np.array(list,dtype=int)
print('Вектор из 36 целых чисел, начиная с 1, каждое последующее на 2 больше предыдущего:')
print(vect)
split = vect[1::3]
print('Вектор из элементов первого вектора, которые кратны 3:')
print(split)

Вектор из 36 целых чисел, начиная с 1, каждое последующее на 2 больше предыдущего:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71]
Вектор из элементов первого вектора, которые кратны 3:
[ 3  9 15 21 27 33 39 45 51 57 63 69]
