In [ ]:
#@title Задание 1
import numpy as np
A = np.mat ([6,-8,3])
B = np.mat([[1],
            [1],
            [4]])
print('MATRIX A = \n',A)
print('MATRIX B =\n',B)
C = A@B
print('A*B =\n',C)

MATRIX A = 
 [[ 6 -8  3]]
MATRIX B =
 [[1]
 [1]
 [4]]
A*B =
 [[10]]


In [ ]:
#@title Задание 2
import numpy as np
A = np.mat ([[-3,-7],[-10,6],[0,-6],[-1,-3]])
B = np.mat([[-8,9],[4,-2]])
print('MATRIX A = \n',A)
print('MATRIX B =\n',B)
C = A@B
print('A*B =\n',C)

MATRIX A = 
 [[ -3  -7]
 [-10   6]
 [  0  -6]
 [ -1  -3]]
MATRIX B =
 [[-8  9]
 [ 4 -2]]
A*B =
 [[  -4  -13]
 [ 104 -102]
 [ -24   12]
 [  -4   -3]]
